/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_serliogiron;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Main extends javax.swing.JFrame {
    static Random random = new Random();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        TextArea.setText("--- mascotas --- \n" + "VACIO \n" + "--- Zonas --- \n" + "VACIO\n" + "--- Items --- \n" + "VACIO");
        hilodetabla = new HiloTable(tabla_mascotas);
    }
    
    static ArrayList <Item> items = new ArrayList();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorchooser = new javax.swing.JColorChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_mascotas = new javax.swing.JTable();
        barra = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crear_mascota_field_nombre = new javax.swing.JTextField();
        crear_mascota_field_puntosvida = new javax.swing.JTextField();
        crear_mascota_field_delay = new javax.swing.JTextField();
        botoncolor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        item_nombre = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        item_obtencion = new javax.swing.JTextField();
        item_costo = new javax.swing.JTextField();
        boton_crear_item = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        zona_nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        zona_derrumbe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        zona_ataque = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_agregar_item = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_items = new javax.swing.JList<>();
        Agregar_item = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        crear_mascota_field_costo = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        comandos_textfield = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_mascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Delay", "Costo", "Puntos de Vida", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla_mascotas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mascota", jPanel1);

        jLabel1.setText("Nombre");

        jLabel2.setText("Puntos de Vida");

        jLabel3.setText("Delay");

        jLabel4.setText("Costo");

        crear_mascota_field_delay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_mascota_field_delayActionPerformed(evt);
            }
        });

        botoncolor.setText("Color");
        botoncolor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncolorMouseClicked(evt);
            }
        });

        jButton2.setText("Crear Mascota");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Crear Mascota");

        jLabel6.setText("Crear Item");

        jLabel7.setText("Nombre");

        jCheckBox1.setText("Alimento");

        jLabel8.setText("Probabilidad de Obtencion");

        jLabel9.setText("Precio de Venta");

        item_costo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item_costoMouseClicked(evt);
            }
        });

        boton_crear_item.setText("Crear Item");
        boton_crear_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_crear_itemMouseClicked(evt);
            }
        });

        jLabel10.setText("Crear Zona");

        jLabel11.setText("Nombre");

        jLabel12.setText("Probabilidad de Derrumbe");

        jLabel13.setText("Probabilidad de Ataque");

        jLabel14.setText("Agregar Item");

        jList_agregar_item.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList_agregar_item);

        jLabel15.setText("Items");

        jList_items.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jList_items);

        Agregar_item.setText("Agregar Item");
        Agregar_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_itemMouseClicked(evt);
            }
        });

        jButton5.setText("Crear Zona");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        crear_mascota_field_costo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(149, 149, 149))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(crear_mascota_field_costo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crear_mascota_field_delay, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crear_mascota_field_puntosvida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(crear_mascota_field_nombre)
                                    .addComponent(botoncolor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(117, 117, 117)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(item_nombre)
                            .addComponent(item_costo)
                            .addComponent(item_obtencion)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(boton_crear_item, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(zona_derrumbe, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(zona_ataque)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(zona_nombre))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Agregar_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, 156))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(306, 306, 306))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crear_mascota_field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zona_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crear_mascota_field_puntosvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)
                            .addComponent(zona_derrumbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crear_mascota_field_delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_obtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zona_ataque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(item_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crear_mascota_field_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botoncolor)
                                    .addComponent(boton_crear_item))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Agregar_item)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administracion", jPanel2);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane4.setViewportView(TextArea);

        comandos_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandos_textfieldActionPerformed(evt);
            }
        });
        comandos_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comandos_textfieldKeyPressed(evt);
            }
        });

        jButton6.setText(">");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comandos_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comandos_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comandos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear_mascota_field_delayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_mascota_field_delayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear_mascota_field_delayActionPerformed

    private void botoncolorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncolorMouseClicked
        colorchooser.setVisible(true);
        
        Color background = colorchooser.showDialog(null, "JColorChooser Sample", botoncolor.getBackground());

        botoncolor.setBackground(background);
    }//GEN-LAST:event_botoncolorMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String nombre = crear_mascota_field_nombre.getText();
        Double costo = Double.parseDouble(crear_mascota_field_costo.getText());
        int delay = Integer.parseInt(crear_mascota_field_delay.getText());
        int vida = Integer.parseInt(crear_mascota_field_puntosvida.getText());
        Color color = botoncolor.getBackground();
        
        Mascota mas = new Mascota(nombre, vida, delay, costo, color);
        mascotas.add(mas);
        
        JOptionPane.showMessageDialog(this, "Mascota agregada");
        
        
        
        crear_mascota_field_nombre.setText("");
        crear_mascota_field_costo.setText("");
        crear_mascota_field_delay.setText("");
        crear_mascota_field_puntosvida.setText("");
        botoncolor.setBackground(Color.gray);
        
        TextArea.setText(limpiarTextArea());
        TextArea.setText(updateTextArea());
        
    }//GEN-LAST:event_jButton2MouseClicked
    static ArrayList <Mascota> mascotas = new ArrayList();
    private void boton_crear_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_crear_itemMouseClicked
        
        String nombre = item_nombre.getText();
        boolean alimento;
        
        if (jCheckBox1.isSelected()) {
            alimento = true;
        }else{
            alimento = false;
        }
        
        double obtenion = Double.parseDouble(item_obtencion.getText());
        double precio = Double.parseDouble(item_costo.getText());
        
        int id = items.size()+1;
        
        Item item = new Item(id, nombre, alimento, obtenion, precio);
        
        items.add(item);
        
        DefaultListModel modelo = new DefaultListModel();
        modelo = (DefaultListModel)jList_agregar_item.getModel();
        
        modelo.addElement(item);
        
        jList_agregar_item.setModel(modelo);
        
        item_nombre.setText("");
        jCheckBox1.setSelected(false);
        item_obtencion.setText("");
        item_costo.setText("");
        
        TextArea.setText(limpiarTextArea());
        TextArea.setText(updateTextArea());
        
    }//GEN-LAST:event_boton_crear_itemMouseClicked
    
    private void item_costoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item_costoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_item_costoMouseClicked
    static ArrayList <Zona> zonas = new ArrayList();
    ArrayList <Item> itemparazonas = new ArrayList();
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        
        String nombre = zona_nombre.getText();
        double derrumbe = Double.parseDouble(zona_derrumbe.getText());
        double atacado = Double.parseDouble(zona_ataque.getText());
        //capturo lo de los fields
        
        Zona zona = new Zona(contzonas, nombre, derrumbe, atacado);
        //creo la zona
        
        //System.out.println("-- itemparazonas --");
        //System.out.println(itemparazonas);
        
        zona.getItems().addAll(itemparazonas);
        //le agrego al objto zona, su lista de items
        zonas.add(zona);
        
        contzonas++;
        
        zona_ataque.setText("");
        zona_derrumbe.setText("");
        zona_nombre.setText("");
        
        for (int i = 0; i < itemparazonas.size(); i++) 
        {
            itemparazonas.remove(i);
        }
        
        DefaultListModel m = new DefaultListModel();
        m = (DefaultListModel)jList_items.getModel();
        m.removeAllElements();
        jList_items.setModel(m);
        
        
        System.out.println("-- zonas --");
        System.out.println(zonas);
        
        TextArea.setText(limpiarTextArea());
        TextArea.setText(updateTextArea());
        
    }//GEN-LAST:event_jButton5MouseClicked
    int contzonas = 1;
    private void Agregar_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_itemMouseClicked
        DefaultListModel modelo = new DefaultListModel();
        modelo = (DefaultListModel)jList_agregar_item.getModel();
        
        DefaultListModel modelo2 = new DefaultListModel();
        modelo2 = (DefaultListModel)jList_items.getModel();
        
        modelo2.addElement(modelo.getElementAt(jList_agregar_item.getSelectedIndex()));
        
        jList_items.setModel(modelo2);
        
        itemparazonas.add((Item)modelo.getElementAt(jList_agregar_item.getSelectedIndex()));
        
        //System.out.println("-- itemparazonas --");
        //System.out.println(itemparazonas);
    }//GEN-LAST:event_Agregar_itemMouseClicked

    private void comandos_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandos_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comandos_textfieldActionPerformed

    private void comandos_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comandos_textfieldKeyPressed
        if (evt.getKeyCode() == 10) {
            //System.out.println("key code");
            TextArea(comandos_textfield.getText());
        }
    }//GEN-LAST:event_comandos_textfieldKeyPressed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        TextArea(comandos_textfield.getText());
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void AgregarMascotaTable(Mascota m){
        Object[] row = new Object[5];
        
        row[0] = m.getNombre();
        row[1] = m.getDelay();
        row[2] = m.getCosto();
        row[3] = m.getVida();
        row[4] = m.getColor();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel)tabla_mascotas.getModel();
        modelo.addRow(row);
        tabla_mascotas.setModel(modelo);
    }
    
    Mascota mascota = new Mascota();
    
    public void TextArea(String s){
        
        String [] token = s.split(" ");
        
        if (s.equals("!clear")) {
            TextArea.setText(limpiarTextArea());
            limpiarComandField();
        }
        else if(token[0].equals("!pet") && token[1].equals("active")){
            String nombre = (String)token[2];
            
            int cont = 0;
            int index = 0;
            DefaultTableModel modelo = new DefaultTableModel();
            modelo = (DefaultTableModel)tabla_mascotas.getModel();
            
            for (int i = 0; i < tabla_mascotas.getRowCount(); i++) {
                if (nombre.equals(modelo.getValueAt(i, 0))) {
                    cont++;
                    index = i;
                }
            }
            
            if (cont > 0) {
                hilodebarra = new HiloBarra(barra, (String)modelo.getValueAt(index, 0), tabla_mascotas);
                hilodebarra.start();
            }
            
            //Mascota m = new Mascota(modelo.getValueAt(index, 0), modelo.getValueAt(index, 1), modelo.getValueAt(index, 2), modelo.getValueAt(index, 3), modelo.getValueAt(index, 4))
            
            limpiarComandField();
        }
        else if(token[0].equals("!pet") && token[1].equals("feed")){
            System.out.println("-- items --");
            System.out.println(items);
            
            int id = Integer.parseInt(token[3]);
            
            if (items.get(id).isAlimento()) {
                
            }
            limpiarComandField();
        }
        else if(token[0].equals("!pet") && token[1].equals("list")){
            System.out.println("!pet list");
            limpiarComandField();
        }
        else if(token[0].equals("!adopt")){
            
            String nombre;
            boolean aver = false;
            int posicion = -1;
            
            for (int i = 0; i < mascotas.size(); i++) {
                nombre = mascotas.get(i).getNombre();
                
                if (nombre.equals(token[1])) {
                    aver = true;
                    posicion = i;
                }
            }
            
            if (aver) {
                Mascota mascota = new Mascota();
                mascota = mascotas.get(posicion);
                AgregarMascotaTable(mascota);
                hilodetabla.start();
            }
            
//            System.out.println("tablarowcount = " + tabla_mascotas.getRowCount());
//            
//            DefaultTableModel modelo = new DefaultTableModel();
//            modelo = (DefaultTableModel)tabla_mascotas.getModel();
//            System.out.println("columna = " + modelo.getValueAt(1, 2));
            
            
            limpiarComandField();
        }
        else if(token[0].equals("!mine")){
            System.out.println("!mine");
            limpiarComandField();
        }
        else if(token[0].equals("!fish")){
            System.out.println("!fish");
            limpiarComandField();
        }
        else if(token[0].equals("!zone") && token[1].equals("list")){
            System.out.println("!zone list");
            limpiarComandField();
        }
        else if(token[0].equals("!sell")){
            System.out.println("!sell idItem");
            limpiarComandField();
        }
        else if(token[0].equals("!item") && token[1].equals("list")){
            System.out.println("!item list");
            limpiarComandField();
        }
        else if(token[0].equals("!buy")){
            System.out.println("!buy");
            limpiarComandField();
        }
        else if(token[0].equals("!bag")){
            System.out.println("!bag");
            limpiarComandField();
        }
        else if(token[0].equals("!d")){
            System.out.println("!d");
            limpiarComandField();
        }
        else if(token[0].equals("!w")){
            System.out.println("!w");
            limpiarComandField();
        }
        else if(token[0].equals("!b")){
            System.out.println("!b");
            limpiarComandField();
        }
        
    }
    
    public void limpiarComandField(){
        comandos_textfield.setText("");
    }
    
    public static String limpiarTextArea(){
        String a = "";
        return a;
    }
    
    public static String updateTextArea(){
        String a = "--- mascotas --- \n" + mascotas + "\n" + "--- Zonas --- \n" + zonas + "\n" +"--- Items --- \n" + items;
        return a;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_item;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton boton_crear_item;
    private javax.swing.JButton botoncolor;
    private javax.swing.JColorChooser colorchooser;
    private javax.swing.JTextField comandos_textfield;
    private javax.swing.JFormattedTextField crear_mascota_field_costo;
    private javax.swing.JTextField crear_mascota_field_delay;
    private javax.swing.JTextField crear_mascota_field_nombre;
    private javax.swing.JTextField crear_mascota_field_puntosvida;
    private javax.swing.JTextField item_costo;
    private javax.swing.JTextField item_nombre;
    private javax.swing.JTextField item_obtencion;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_agregar_item;
    private javax.swing.JList<String> jList_items;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabla_mascotas;
    private javax.swing.JTextField zona_ataque;
    private javax.swing.JTextField zona_derrumbe;
    private javax.swing.JTextField zona_nombre;
    // End of variables declaration//GEN-END:variables

HiloTable hilodetabla;
HiloBarra hilodebarra;

}
